SELECT COUNT(*) FROM Job;
SELECT COUNT(*) FROM Student;
SELECT COUNT(*) FROM Company;
SELECT COUNT(*) FROM CareerEvent;
SELECT COUNT(*) FROM Source;
SELECT COUNT(*) FROM SearchJ;
SELECT COUNT(*) FROM SearchE;